// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsxUSeuQ_i0kkCdRjeNheUMztMnUKWwDY',
    appId: '1:158376232779:web:41dca6b7d9b864503e8ace',
    messagingSenderId: '158376232779',
    projectId: 'instaclone-f2f27',
    authDomain: 'instaclone-f2f27.firebaseapp.com',
    storageBucket: 'instaclone-f2f27.appspot.com',
    measurementId: 'G-BCHT9ZHKDF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBv_UiEBUAJrCTniZwDWEhNeAJ93cmWPDk',
    appId: '1:158376232779:android:7f247faeba1ccb4b3e8ace',
    messagingSenderId: '158376232779',
    projectId: 'instaclone-f2f27',
    storageBucket: 'instaclone-f2f27.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDrz7SFi8kAT9w31LxuANAAn3jyTulORk',
    appId: '1:158376232779:ios:1c436be7fdea55a73e8ace',
    messagingSenderId: '158376232779',
    projectId: 'instaclone-f2f27',
    storageBucket: 'instaclone-f2f27.appspot.com',
    iosClientId: '158376232779-7t7bpjkqnverquacls1f9rl2fpllihjc.apps.googleusercontent.com',
    iosBundleId: 'com.instaclone.instaClone',
  );
}
